# three separate fact tasks since each depends on the previous
#
# note: timestamp is declared as a fact so it will not be reevaluated,
# between tasks. request_body and backup_location also declared as facts
# since they should not change as well.
#
# note: should be able to create a timestamp without the pipe below by
# filtering a format to strftime but the strftime filter is supported in
# Ansible 2.4+ but we only have 2.3.
- set_fact:
    timestamp: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"

- set_fact:
    backup_location: "{{ backup_location }}{{ timestamp }}"

- debug: msg="timstamp = {{ timestamp }}"
- debug: msg="configuration_path = {{ configuration_path }}"
- debug: msg="repository_path = {{ repository_path }}"
- debug: msg="backup_location = {{ backup_location }}"
- debug: msg="request_body = {{ request_body }}"

- name: check if host is reachable
  wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ hostvars[inventory_hostname]['http_port'] | default(8080) }}"

- name: back up designated Magnolia instance
  uri:
    url: "http://{{ inventory_hostname }}:{{ hostvars[inventory_hostname]['http_port'] | default(8080) }}/{{ backup_uri }}"
    method: POST
    body_format: json
    body: "{{ request_body }}"
    user: "{{ magnolia_user }}"
    password: "{{ magnolia_password }}"
    force_basic_auth: yes
    status_code: 200
