---
- name: Load AWS keys
  include_vars: "aws_keys.yml"

- name: Provision EC2 instance(s)
  local_action: ec2
    aws_access_key={{ magnolia_aws_access_key }}
    aws_secret_key={{ magnolia_aws_secret_key }}
    group={{ aws_security_group }}
    instance_type={{ aws_instance_type }}
    image={{ aws_image }}
    wait=true
    region={{ aws_region }}
    keypair={{ aws_keypair }}
    count={{ num_servers }}
  register: ec2

# NOTE: the following does NOT update the actual hosts file
- name: Add the newly created EC2 instance(s) to the specified group
  add_host:
    hostname: "{{ item.public_ip }}"
    groups: "{{ server_group }}"
    ansible_user: "ec2-user"
    ansible_ssh_private_key_file: "{{ keypairs_location }}/{{ keypair_file }}.pem"
  with_items: "{{ ec2.instances }}"

- name: Wait for SSH to come up
  local_action: wait_for
                host={{ item.public_ip }}
                port=22
                state=started
  when: wait_for_ssh
  with_items: "{{ ec2.instances }}"
