- name: Add the newly created EC2 instance(s) to the local host group (located inside the directory)
  local_action: lineinfile
                dest="{{ hosts_file }}"
                regexp={{ item.public_ip }}
                insertafter="[{{ servergroup }}]" line="{{ item.public_ip }} ansible_user=ec2-user ansible_ssh_private_key_file={{ keypairs_location }}/{{ keypair }}.pem"
  with_items: "{{ ec2.instances }}"
