# Magnolia user/password to use for REST call
magnolia_user: superuser
magnolia_password: superuser
# REST call URI
create_node_uri: ".rest/nodes/v1/config/server/activation/subscribers"
# subscriber name construction
subscriber_prefix: "myPublic"
subscriber_name: "{{ subscriber_prefix }}-{{ hostvars[item].inventory_hostname | regex_replace('\\.','-') }}-{{ hostvars[item].http_port | default(default_http_port) }}"
subscriber2_name: "{{ subscriber_prefix }}-{{ hostvars[item[1]].inventory_hostname | regex_replace('\\.','-') }}-{{ hostvars[item[1]].http_port | default(default_http_port) }}"
context_path: "magnoliaPublic"
default_http_port: 8080
#
# template for top level subscriber node
#
subscriber_node: {
  name: "{{ subscriber_name }}",
  type: "mgnl:contentNode",
  properties: [
    {
      name: "active",
      type: "String",
      multiple: false,
      values: [
        "false"
      ]
    },
    {
      name: "class",
      type: "String",
      multiple: false,
      values: [
        "info.magnolia.module.activation.DefaultSubscriber"
      ]
    },
    {
      name: "URL",
      type: "String",
      multiple: false,
      values: [
        "http://{{hostvars[item].inventory_hostname}}:{{ hostvars[item].http_port | default(default_http_port) }}/{{ context_path }}"
      ]
    }
  ]
}
#
# template for subscriptions subnode
#
subscriptions_node: {
  name: "subscriptions",
  type: "mgnl:contentNode",
  properties: []
}
#
# template for targeted subscriptions subnodes
#
subscriptions: [
  {
    name: "exampleSubSiteSubscription",
    type: "mgnl:contentNode",
    properties: [
      {
        name: "toURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      },
      {
        name: "repository",
        type: "String",
        multiple: false,
        values: [
          "website"
        ]
      },
      {
        name: "fromURI",
        type: "String",
        multiple: false,
        values: [
          "/site2"
        ]
      }
    ]
  },
  {
    name: "websiteSubscription",
    type: "mgnl:contentNode",
    properties: [
      {
        name: "toURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      },
      {
        name: "repository",
        type: "String",
        multiple: false,
        values: [
          "website"
        ]
      },
      {
        name: "fromURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      }
    ]
  },
  {
    name: "configSubscription",
    type: "mgnl:contentNode",
    properties: [
      {
        name: "toURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      },
      {
        name: "repository",
        type: "String",
        multiple: false,
        values: [
          "config"
        ]
      },
      {
        name: "fromURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      }
    ]
  },
  {
    name: "usersSubscription",
    type: "mgnl:contentNode",
    properties: [
      {
        name: "toURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      },
      {
        name: "repository",
        type: "String",
        multiple: false,
        values: [
          "users"
        ]
      },
      {
        name: "fromURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      }
    ]
  },
  {
    name: "userRolesSubscription",
    type: "mgnl:contentNode",
    properties: [
      {
        name: "toURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      },
      {
        name: "repository",
        type: "String",
        multiple: false,
        values: [
          "userroles"
        ]
      },
      {
        name: "fromURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      }
    ]
  },
  {
    name: "userGroupsSubscription",
    type: "mgnl:contentNode",
    properties: [
      {
        name: "toURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      },
      {
        name: "repository",
        type: "String",
        multiple: false,
        values: [
          "usergroups"
        ]
      },
      {
        name: "fromURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      }
    ]
  },
  {
    name: "resources",
    type: "mgnl:contentNode",
    properties: [
      {
        name: "repository",
        type: "String",
        multiple: false,
        values: [
          "resources"
        ]
      },
      {
        name: "fromURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      },
      {
        name: "toURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      }
    ]
  },
  {
    name: "dms",
    type: "mgnl:contentNode",
    properties: [
      {
        name: "repository",
        type: "String",
        multiple: false,
        values: [
          "dms"
        ]
      },
      {
        name: "fromURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      },
      {
        name: "toURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      }
    ]
  },
  {
    name: "dam",
    type: "mgnl:contentNode",
    properties: [
      {
        name: "repository",
        type: "String",
        multiple: false,
        values: [
          "dam"
        ]
      },
      {
        name: "fromURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      },
      {
        name: "toURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      }
    ]
  },
  {
    name: "imaging",
    type: "mgnl:contentNode",
    properties: [
      {
        name: "repository",
        type: "String",
        multiple: false,
        values: [
          "imaging"
        ]
      },
      {
        name: "fromURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      },
      {
        name: "toURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      }
    ]
  },
  {
    name: "tasks",
    type: "mgnl:contentNode",
    properties: [
      {
        name: "repository",
        type: "String",
        multiple: false,
        values: [
          "tasks"
        ]
      },
      {
        name: "fromURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      },
      {
        name: "toURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      }
    ]
  },
  {
    name: "messages",
    type: "mgnl:contentNode",
    properties: [
      {
        name: "repository",
        type: "String",
        multiple: false,
        values: [
          "messages"
        ]
      },
      {
        name: "fromURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      },
      {
        name: "toURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      }
    ]
  },
  {
    name: "profiles",
    type: "mgnl:contentNode",
    properties: [
      {
        name: "repository",
        type: "String",
        multiple: false,
        values: [
          "profiles"
        ]
      },
      {
        name: "fromURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      },
      {
        name: "toURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      }
    ]
  },
  {
    name: "scripts",
    type: "mgnl:contentNode",
    properties: [
      {
        name: "repository",
        type: "String",
        multiple: false,
        values: [
          "scripts"
        ]
      },
      {
        name: "fromURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      },
      {
        name: "toURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      }
    ]
  },
  {
    name: "templates",
    type: "mgnl:contentNode",
    properties: [
      {
        name: "repository",
        type: "String",
        multiple: false,
        values: [
          "templates"
        ]
      },
      {
        name: "fromURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      },
      {
        name: "toURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      }
    ]
  },
  {
    name: "contacts",
    type: "mgnl:contentNode",
    properties: [
      {
        name: "repository",
        type: "String",
        multiple: false,
        values: [
          "contacts"
        ]
      },
      {
        name: "fromURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      },
      {
        name: "toURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      }
    ]
  },
  {
    name: "googleSitemaps",
    type: "mgnl:contentNode",
    properties: [
      {
        name: "repository",
        type: "String",
        multiple: false,
        values: [
          "googleSitemaps"
        ]
      },
      {
        name: "fromURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      },
      {
        name: "toURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      }
    ]
  },
  {
    name: "advancedCache",
    type: "mgnl:contentNode",
    properties: [
      {
        name: "repository",
        type: "String",
        multiple: false,
        values: [
          "advancedCache"
        ]
      },
      {
        name: "fromURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      },
      {
        name: "toURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      }
    ]
  },
  {
    name: "forum",
    type: "mgnl:contentNode",
    properties: [
      {
        name: "repository",
        type: "String",
        multiple: false,
        values: [
          "forum"
        ]
      },
      {
        name: "fromURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      },
      {
        name: "toURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      }
    ]
  },
  {
    name: "tags",
    type: "mgnl:contentNode",
    properties: [
      {
        name: "repository",
        type: "String",
        multiple: false,
        values: [
          "tags"
        ]
      },
      {
        name: "fromURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      },
      {
        name: "toURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      }
    ]
  },
  {
    name: "rss",
    type: "mgnl:contentNode",
    properties: [
      {
        name: "repository",
        type: "String",
        multiple: false,
        values: [
          "rss"
        ]
      },
      {
        name: "fromURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      },
      {
        name: "toURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      }
    ]
  },
  {
    name: "workflow",
    type: "mgnl:contentNode",
    properties: [
      {
        name: "repository",
        type: "String",
        multiple: false,
        values: [
          "workflow"
        ]
      },
      {
        name: "fromURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      },
      {
        name: "toURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      }
    ]
  },
  {
    name: "category",
    type: "mgnl:contentNode",
    properties: [
      {
        name: "repository",
        type: "String",
        multiple: false,
        values: [
          "category"
        ]
      },
      {
        name: "fromURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      },
      {
        name: "toURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      }
    ]
  },
  {
    name: "segments",
    type: "mgnl:contentNode",
    properties: [
      {
        name: "repository",
        type: "String",
        multiple: false,
        values: [
          "segments"
        ]
      },
      {
        name: "fromURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      },
      {
        name: "toURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      }
    ]
  },
  {
    name: "personas",
    type: "mgnl:contentNode",
    properties: [
      {
        name: "repository",
        type: "String",
        multiple: false,
        values: [
          "personas"
        ]
      },
      {
        name: "fromURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      },
      {
        name: "toURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      }
    ]
  },
  {
    name: "tours",
    type: "mgnl:contentNode",
    properties: [
      {
        name: "repository",
        type: "String",
        multiple: false,
        values: [
          "tours"
        ]
      },
      {
        name: "fromURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      },
      {
        name: "toURI",
        type: "String",
        multiple: false,
        values: [
          "/"
        ]
      }
    ]
  }
]
