---
  - name: Back up a specified Magnolia app
    hosts: "{{ host_group | default('local') }}"
    connection: local
    gather_facts: False
    tags: provisioning

    vars:
      backup_uri: ".rest/commands/v2/backup/xbackup"
      magnolia_user: superuser
      magnolia_password: superuser

    tasks:
      - include: tasks/rest_backup_task.yml

      - include: tasks/zip_directory_task.yml
        vars:
          target_path: "{{ backup_location }}"
          target_dest: "{{ backup_location }}.zip"
