# ansible-playbook playbooks/examples/create_public.yml -i aws-hosts --ask-vault-pass
  
  - name: Provision an EC2 instance(s) for Magnolia public instance(s)
    hosts: local
    connection: local
    gather_facts: False
    tags: provisioning

    # Encrypted variables for AWS access
    vars_files:
      - bda-vars.yml

    # Tasks to create EC2 instance, record it in our host file and wait for SSH to start
    tasks:
      - name: include variables
        include_vars: vars.yml
      - include: create_ec2.yml
      - include: add_ec2_host.yml 
      - include: wait_for_ssh.yml

  - include: java_install.yml       # install java
  - include: tomcat_install.yml     # install tomcat
  - include: setup_magnolia.yml     # add magnolia and some spices
