- hosts: [publicservers]
  tasks:
    - name: include variables
      include_vars: vars.yml
    - name: add magnoliaPublic database
      mysql_db: 
        name: magnoliaPublic 
        state: present
        login_user: root 
        login_password: "{{ mysql_password }}"
